 if(WIN32)
    set(SEARCH_PATH "$ENV{ProgramW6432}\\7-Zip")
    find_program(ZIP_EXECUTABLE 7z PATHS "${SEARCH_PATH}") 
    if(ZIP_EXECUTABLE)
      message("file archiver: ${ZIP_EXECUTABLE}")
    else()
      message(FATAL_ERROR "can't found 7z in ${SEARCH_PATH}, cmake will exit")
    endif()
      set(ZIP_COMMAND "\"${ZIP_EXECUTABLE}\" x \"${TARGET_FILE}\" -o\"${TEMP_DIRECTORY}\" -r")
  else()
    set(ZIP_COMMAND "unzip \"${TARGET_FILE}\" -d \"${TEMP_DIRECTORY}\"")
  endif()